name: cotfm
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python
  - numpy
  - pytorch
  - pytorch-cuda
  - torchaudio
  - torchvision
  - matplotlib
  - scipy
  - lightning
  - pysteps
  - pip
  - fenics-dolfinx
  - mpich
  - petsc
  - mpi4py
  - hdf5>=1.12.2
  - pip:
    - tqdm==4.64
    - torchcfm
    - torchdiffeq
    - jaxtyping
    - gpytorch
    - properscoring
    - wandb